site_name: EA8DHY
docs_dir: '../../docs/es'
site_dir: '../../generated/es'
site_url: https://www.ea8dhy.es/es
site_description: Web personal de EA8DHY
site_author: EA8DHY

theme:
  name: material
  custom_dir: '../../overrides/'
  language: es
  palette:
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/lightbulb-outline
        name: Cambiar al modo claro
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/lightbulb
        name: Cambiar al modo oscuro


extra:
  alternate:
    #switch to English
    - name: English
      link: /en/
      lang: en
    #switch to Spanish
    - name: Spanish
      link: /es/
      lang: es