site_name: EA8DHY
site_url: https://www.ea8dhy.es
site_descripcion: Personal website from EA8DHY
site_author: EA8DHY

theme:
  name: material
  palette:
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
