# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install mkdocs
        run: pip install mkdocs-material
      - name: Build English version
        run: mkdocs build -f config/en/mkdocs.yml
      - name: Build Spanish version
        run: mkdocs build -f config/es/mkdocs.yml
      - name: Copy redirector index and CNAME
        run: cp index.html generated/index.html && cp CNAME generated/CNAME
      - name: show directory
        run: ls
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: 'generated'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
