# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs build -f config/en/mkdocs.yml
      - run: mkdocs build -f config/es/mkdocs.yml
      - run: cp index.html generated/index.html && cp CNAME generated/CNAME
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: gh-pages
          file_pattern: 'generated/*'
          push_options: '--force'
          skip_fetch: true
